### ISSUE TITLE
Error msg Jquery 3.1

### ISSUE THREAD

**Issue by Helge85** [gijsroge/Swiper-Thumbnails#1]
Thx for your plugin, it solved a problem i was hunting for hours!
but since i implemented your plugin in i get the following error msg. How can i solve this problem?

![bildschirmfoto 2017-01-27 um 15 53 51](https://cloud.githubusercontent.com/assets/25309659/22373678/2e388a80-e4a3-11e6-8c50-fd3e764fbac8.png)

**Comment by gijsroge** [comment]
I can't really help you if you don't provide a full demo that reproduces this. Link a codepen or fiddle please! thanks.

**Comment by Helge85** [comment]
the problem occurs here http://studio-a-h.de/kirby-test/
