### ISSUE TITLE
does is-active work?

### ISSUE THREAD

**Issue by giles247** [gijsroge/Swiper-Thumbnails#4]
Even on the demo only the first thumbnail is assigned class 'is-active' andthis doesn't seem to change regardless of what slide or thimbnail is selected. My assumption was that thumbnail corresponding to current main slide selected would always be 'is-active' or have I got this wrong?

**Comment by giles247** [comment]
Ok, fixed it by changing event name on line 84 to just slideChange.
Not sure if this was maybe due to event name change in later version

**Comment by gijsroge** [comment]
@redactuk Thanks for the heads up, this is indeed an api change.
